repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: .*docker-compose.*?y(am|m)l

      - id: end-of-file-fixer
        files: .*\.py

      - id: trailing-whitespace
        files: .*\.py

  - repo: local
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        language_version: python3
        require_serial: true
        types: [ python ]
